### ISSUE TITLE
Repo setup

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#1]
Make sure everyone can clone, and install the repo on their ends.

**Comment by usmanwardag** [comment]
Document here if anyone has any issues with the repo setup.

**Comment by usmanwardag** [comment]
I was able to setup without issues.

**Comment by aakriti0fnu** [comment]
i was also able to setup without issues

**Comment by sbosenc** [comment]
Able to set up the repo.

**Comment by muskan7828** [comment]
Was able to set up the repo without issues.

**Comment by usmanwardag** [comment]
Closing.
