### ISSUE TITLE
UI / UX - Provide more flexibility for date input

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#15]

**Comment by aakriti0fnu** [comment]
@usmanwardag - is this related to adding calendar functionality?

**Comment by usmanwardag** [comment]
Yeah, but adding the calendar may be difficult. So the idea is to just explore if there are alternative ways for inputting dates which are a bit easier.

**Comment by aakriti0fnu** [comment]
Old date input method
![old_dateformat](https://user-images.githubusercontent.com/65619749/143719829-dec06672-6036-4918-b6a2-a58356eddb9d.png)

New date input method - calendar
![updatedcalendar](https://user-images.githubusercontent.com/65619749/143719858-49a84d97-6083-442c-bca1-c4031138ddb1.png)

![day](https://user-images.githubusercontent.com/65619749/143719863-8ec06dc8-5849-435d-b778-82f39abfdf2c.png)

**Comment by aakriti0fnu** [comment]
Calendar functionality added!
