### ISSUE TITLE
Python code documentation

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#19]

**Comment by aakriti0fnu** [comment]
@usmanwardag - do we have to add docstrings to the code?
we have an issue for generating automatic documentation and for that we must have docstrings in the code then what would be the purpose of this documentation

**Comment by usmanwardag** [comment]
Ok this issue may be a duplicate then

**Comment by usmanwardag** [comment]
Closing as it is duplicate of #21
