### ISSUE TITLE
Bot Setup

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#2]
Make sure that we can replicate bot functionalities implemented by the previous groups.

**Comment by usmanwardag** [comment]
Document here if anyone has any issues.

**Comment by usmanwardag** [comment]
I was able to install the bot on Telegram.

**Comment by aakriti0fnu** [comment]
installed bot on telegram

**Comment by sbosenc** [comment]
installed and ran the bot on Telegram.

**Comment by muskan7828** [comment]
Implemented and ran bot on telegram.

**Comment by usmanwardag** [comment]
Closing.
