### ISSUE TITLE
Tests for new features

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#29]

**Comment by usmanwardag** [comment]
@muskan7828 @aakriti0fnu @kriti0207 @sbosenc Is this done?

**Comment by usmanwardag** [comment]
If not, then let's mention this for future work.

**Comment by sbosenc** [comment]
Added adequate test cases. The current code coverage is 90%. It could be further improved.

**Comment by usmanwardag** [comment]
Ok. Closing.
