### ISSUE TITLE
Telegram Integration

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#5]

**Comment by usmanwardag** [comment]
Telegram and bot integration.

**Comment by usmanwardag** [comment]
Document here if anyone has any issues.

**Comment by usmanwardag** [comment]
I was able to do the integration.

**Comment by sbosenc** [comment]
Integration done without any issues.

**Comment by muskan7828** [comment]
Was able to do the telegram integration.

**Comment by aakriti0fnu** [comment]
successful integration

**Comment by usmanwardag** [comment]
Closing.
