### ISSUE TITLE
UI - Add improved messages for each bot command

### ISSUE THREAD

**Issue by usmanwardag** [usmanwardag/dollar_bot#9]

**Comment by aakriti0fnu** [comment]
@usmanwardag - Could you provide a little description of where the issue is pointing

**Comment by usmanwardag** [comment]
Basically, whenever user types a command on Telegram, they are shown a certain message (e.g., telling them about their expenses, or how much budget they have left).

The idea of this task is to make those messages more detailed, more informative etc.

**Comment by aakriti0fnu** [comment]
Old Bot messages:
![Old_botmessage](https://user-images.githubusercontent.com/65619749/143726333-61b3c3ec-e1be-4925-b838-5ba73ee7df32.png)

Improved Bot messages:
![Improved_botmessage](https://user-images.githubusercontent.com/65619749/143726339-6261b440-fd93-4e57-8092-fb5ef662b0b9.png)
